services:
  app:
    build: .
    container_name: thresherr-app
    ports:
      - "8505:8000"
    volumes:
      - ./app:/app
      - /multimedia:/media
      - /temp:/temp
    restart: unless-stopped

  worker:
    build: .
    container_name: thresherr-worker
    command: ["python", "worker.py"]
    volumes:
      - ./app:/app
      - /multimedia:/media
      - /temp:/temp
    depends_on:
      - app
    restart: unless-stopped
